<!doctype html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <base href="<?php echo \NG\Uri::baseUrl();?>" />
        <title>NG Framework</title>
        <meta name="description" content="">
        <meta name="author" content="">

        <meta name="viewport" content="width=device-width">

        <link rel="stylesheet" href="Assets/css/bootstrap.min.css">
        <link rel="stylesheet" href="Assets/css/bootstrap-responsive.min.css">
        <link rel="stylesheet" href="Assets/css/style.css">

        <script src="Assets/js/libs/modernizr-2.5.3-respond-1.1.0.min.js"></script>
    </head>
    <body>
    <!--[if lt IE 7]><p class=chromeframe>Your browser is <em>ancient!</em> <a href="http://browsehappy.com/">Upgrade to a different browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to experience this site.</p><![endif]-->

        <div class="navbar navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container-fluid">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="#">NG Framework</a>
                    <div class="nav-collapse">
                        <ul class="nav">

                        </ul>
                    </div><!--/.nav-collapse -->
                </div>
            </div>
        </div>

        <div class="container">
            <?php
            $this->render();
            ?>


            <!-- Example row of columns -->
            <div class="row">
                <div class="span12">

                </div>
            </div>

            <hr>



        </div> <!-- /container -->
        <footer>
            <p align="center">&copy; NG Framework <?php echo date("Y")?></p>
        </footer>

        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="Assets/js/libs/jquery-1.7.2.min.js"><\/script>')</script>
        <script src="Assets/js/libs/bootstrap/bootstrap.min.js"></script>
        <script src="Assets/js/script.js"></script>        
    </body>
</html>
